### ISSUE TITLE
Research state-of-the-art regarding knowledge graph for recommendation systems.

### ISSUE THREAD

**Issue by jonasdacruz** [konstellation-io/kdl#10]

**Comment by gabmunrio** [comment]
After a first review, following there are two promising work lines:
- Work with Graph Knowledge embeddings along to _Common_ embeddings for enrich the input vector for the models
- Use Reinforcement Learning along with the Knowledge Graph (https://arxiv.org/abs/1906.05237)

**Comment by gabmunrio** [comment]
Next steps:

- [ ] Study the RL & KG paper
- [ ] Study different KG embedding techniques to evaluate each of them
- [ ] Design and implement a toy example for checking the performance of these techniques

**Comment by IGZEnriqueRomera** [comment]
https://docs.google.com/presentation/d/1NWvO6zMU-41oW6HoBdwiKtv_olIFrD15SFo1TVvJULM/edit?usp=sharing
