### ISSUE TITLE
Get server data from env variables

### ISSUE THREAD

**Issue by marco-gattelli** [konstellation-io/kdl#153]
We will get the server name and the URL for the graphQl API from the env variables.
@mgs95 @danielchg @angelsanchez @IGZangelcostales how we should call the env vars?
`REACT_APP_SERVER_NAME` for the server name
`REACT_APP_GRAPHQL_URL` for the url of the API
what do you think?

**Comment by angelsanchez** [comment]
![imagen](https://user-images.githubusercontent.com/2531787/106606161-15179700-6562-11eb-9d6a-aca7a413879a.png)
