### ISSUE TITLE
Update knowledge regarding LDAP and OIDC

### ISSUE THREAD

**Issue by jonasdacruz** [konstellation-io/kdl#61]
Sooner than later we will need to allow integration with LDAP and maybe with OIDC, so everyone in the team must update their knowledge about both, including several implementations easy to add in KDL and KRE.

**Comment by guumaster** [comment]
Some read material: 

* [OAuth 2.0, OpenID Connect y JSON Web Tokens (JWT) ¿Qué es qué?](https://www.returngis.net/2019/04/oauth-2-0-openid-connect-y-json-web-tokens-jwt-que-es-que/)
* [Golang: OAuth2 & OpenID. Use OAuth2 & OpenID connect](https://medium.com/scum-gazeta/golang-oauth2-openid-d69d09cb84db)
* [go-ldap/ldap: Basic LDAP v3 Golang](https://github.com/go-ldap/ldap)
